# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: hotel1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-nginx
  template:
    metadata:
      labels:
        app: lab-nginx
    spec:
      containers:
      - name: ken-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env: # <--- 在這裡新增環境變數
        - name: TZ
          value: Asia/Taipei
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "300m"
            memory: "1024Mi"

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: hotel1
spec:
  selector:
    app: lab-nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---
# ingress.yaml
apiVersion: v1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: hotel1
#  annotations:
#    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: hotel1-test.eztravel.com.tw # <-- 請替換為您的實際網域
    http:
      paths:
      - path: /
        pathType: Prefix # Prefix 允許匹配該路徑及其子路徑
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
