# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ken-nginx-deployment
  namespace: ken-nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ken-nginx
  template:
    metadata:
      labels:
        app: ken-nginx
    spec:
      containers:
      - name: ken-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
		resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "300m"
            memory: "1024Mi"

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ken-nginx-service
  namespace: ken-nginx-test
spec:
  selector:
    app: ken-nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
